use std::fs;
use std::path::Path;

fn main() {
    let wkt_dir = Path::new("data-raw/EPSG-v12_054-WKT");

    // Collect all EPSG-CRS-*.wkt files
    let mut files: Vec<_> = fs::read_dir(wkt_dir)
        .unwrap_or_else(|e| panic!("Failed to read {}: {e}", wkt_dir.display()))
        .filter_map(|entry| {
            let entry = entry.ok()?;
            let name = entry.file_name().into_string().ok()?;
            if name.starts_with("EPSG-CRS-") && name.ends_with(".wkt") {
                Some(name)
            } else {
                None
            }
        })
        .collect();
    files.sort();

    println!("Found {} CRS files", files.len());

    let mut wkt_output = String::new();
    let mut json_output = String::new();

    let header = |s: &mut String, kind: &str| {
        s.push_str(
            "// Generated by `cargo run -p generate-definitions`. Do not edit manually.\n\n",
        );
        s.push_str(&format!(
            "//! Auto-generated EPSG CRS definitions ({kind}).\n"
        ));
        s.push_str("//!\n");
        s.push_str("//! The EPSG Dataset is owned by the International Association of Oil & Gas\n");
        s.push_str("//! Producers (IOGP). The source definitions were downloaded from\n");
        s.push_str("//! <https://epsg.org/download-dataset.html>.\n\n");
    };
    header(&mut wkt_output, "WKT2");
    header(&mut json_output, "PROJJSON");

    let mut entries = Vec::new();
    let mut skipped = 0u32;

    for filename in &files {
        let path = wkt_dir.join(filename);
        let wkt = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("Failed to read {}: {e}", path.display()));
        let wkt = wkt.trim();

        // Only process PROJCRS definitions (skip GEOGCRS, VERTCRS, etc.)
        if !wkt.starts_with("PROJCRS[") {
            skipped += 1;
            continue;
        }

        let crs = match epsg_utils::parse_wkt2(wkt) {
            Ok(crs) => crs,
            Err(e) => {
                eprintln!("  WARN: skipping {} (parse error: {e})", filename);
                skipped += 1;
                continue;
            }
        };

        let projjson = serde_json::to_string(&crs.to_projjson())
            .unwrap_or_else(|e| panic!("Failed to serialize {}: {e}", path.display()));

        // Extract EPSG code from filename: EPSG-CRS-6678.wkt -> 6678
        let code: i32 = filename
            .strip_prefix("EPSG-CRS-")
            .and_then(|s| s.strip_suffix(".wkt"))
            .and_then(|s| s.parse().ok())
            .unwrap_or_else(|| panic!("Cannot extract EPSG code from {filename}"));

        // WKT2 constant
        wkt_output.push_str(&format!("/// EPSG:{code} — {}\n", crs.name));
        wkt_output.push_str(&format!("const EPSG_{code}: &str = r#\"{wkt}\"#;\n\n"));

        // PROJJSON constant
        json_output.push_str(&format!("/// EPSG:{code} — {}\n", crs.name));
        json_output.push_str(&format!("const EPSG_{code}: &str = r#\"{projjson}\"#;\n\n"));

        entries.push(code);
    }

    // Generate lookup functions
    let gen_lookup = |s: &mut String| {
        s.push_str("pub(crate) fn lookup(code: i32) -> Option<&'static str> {\n");
        s.push_str("    match code {\n");
        for code in &entries {
            s.push_str(&format!("        {code} => Some(EPSG_{code}),\n"));
        }
        s.push_str("        _ => None,\n");
        s.push_str("    }\n");
        s.push_str("}\n");
    };
    gen_lookup(&mut wkt_output);
    gen_lookup(&mut json_output);

    let write_file = |path: &str, content: &str| {
        let p = Path::new(path);
        fs::write(p, content).unwrap_or_else(|e| panic!("Failed to write {}: {e}", p.display()));
        println!("Generated {path}");
    };
    write_file("src/wkt2_definitions.rs", &wkt_output);
    write_file("src/projjson_definitions.rs", &json_output);

    println!(
        "{} PROJCRS entries generated, {} files skipped",
        entries.len(),
        skipped
    );
}
