// Generated by `cargo run -p generate-definitions`. Do not edit manually.

//! Auto-generated EPSG CRS definitions (PROJJSON).
//!
//! The EPSG Dataset is owned by the International Association of Oil & Gas
//! Producers (IOGP). The source definitions were downloaded from
//! <https://epsg.org/download-dataset.html>.

/// EPSG:6678 — JGD2011 / Japan Plane Rectangular CS X
const EPSG_6678: &str = r#"{"$schema":"https://proj.org/schemas/v0.7/projjson.schema.json","base_crs":{"datum":{"ellipsoid":{"id":{"authority":"EPSG","code":7019},"inverse_flattening":298.257222101,"name":"GRS 1980","semi_major_axis":{"unit":"metre","value":6378137.0}},"id":{"authority":"EPSG","code":1128},"name":"Japanese Geodetic Datum 2011","type":"GeodeticReferenceFrame"},"id":{"authority":"EPSG","code":6668},"name":"JGD2011","type":"GeographicCRS"},"conversion":{"id":{"authority":"EPSG","code":17810},"method":{"id":{"authority":"EPSG","code":9807},"name":"Transverse Mercator"},"name":"Japan Plane Rectangular CS zone X","parameters":[{"id":{"authority":"EPSG","code":8801},"name":"Latitude of natural origin","unit":"degree","value":40.0},{"id":{"authority":"EPSG","code":8802},"name":"Longitude of natural origin","unit":"degree","value":140.833333333334},{"id":{"authority":"EPSG","code":8805},"name":"Scale factor at natural origin","unit":"unity","value":0.9999},{"id":{"authority":"EPSG","code":8806},"name":"False easting","unit":"metre","value":0.0},{"id":{"authority":"EPSG","code":8807},"name":"False northing","unit":"metre","value":0.0}]},"coordinate_system":{"axis":[{"abbreviation":"X","direction":"north","name":"Northing","unit":"metre"},{"abbreviation":"Y","direction":"east","name":"Easting","unit":"metre"}],"id":{"authority":"EPSG","code":4530},"subtype":"Cartesian"},"id":{"authority":"EPSG","code":6678},"name":"JGD2011 / Japan Plane Rectangular CS X","type":"ProjectedCRS"}"#;

pub(crate) fn lookup(code: i32) -> Option<&'static str> {
    match code {
        6678 => Some(EPSG_6678),
        _ => None,
    }
}
