// Generated by `cargo run -p generate-definitions`. Do not edit manually.

//! Auto-generated EPSG CRS definitions (WKT2).
//!
//! The EPSG Dataset is owned by the International Association of Oil & Gas
//! Producers (IOGP). The source definitions were downloaded from
//! <https://epsg.org/download-dataset.html>.

/// EPSG:6678 — JGD2011 / Japan Plane Rectangular CS X
const EPSG_6678: &str = r#"PROJCRS["JGD2011 / Japan Plane Rectangular CS X",BASEGEOGCRS["JGD2011",DATUM["Japanese Geodetic Datum 2011",ELLIPSOID["GRS 1980",6378137,298.257222101,LENGTHUNIT["metre",1,ID["EPSG",9001]],ID["EPSG",7019]],ID["EPSG",1128]],ID["EPSG",6668]],CONVERSION["Japan Plane Rectangular CS zone X",METHOD["Transverse Mercator",ID["EPSG",9807]],PARAMETER["Latitude of natural origin",40,ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9102]],ID["EPSG",8801]],PARAMETER["Longitude of natural origin",140.833333333334,ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9102]],ID["EPSG",8802]],PARAMETER["Scale factor at natural origin",0.9999,SCALEUNIT["unity",1,ID["EPSG",9201]],ID["EPSG",8805]],PARAMETER["False easting",0,LENGTHUNIT["metre",1,ID["EPSG",9001]],ID["EPSG",8806]],PARAMETER["False northing",0,LENGTHUNIT["metre",1,ID["EPSG",9001]],ID["EPSG",8807]],ID["EPSG",17810]],CS[Cartesian,2,ID["EPSG",4530]],AXIS["Northing (X)",north],AXIS["Easting (Y)",east],LENGTHUNIT["metre",1,ID["EPSG",9001]],ID["EPSG",6678]]"#;

pub(crate) fn lookup(code: i32) -> Option<&'static str> {
    match code {
        6678 => Some(EPSG_6678),
        _ => None,
    }
}
